### PR TITLE
wip: circleci deploy process

### PR DESCRIPTION
**Pull request by olizilla**
WIP on #293 - move dnslink deploy to circleci

License: MIT
Signed-off-by: Oli Evans <oli@tableflip.io>

### CODE REVIEW

**Comment by olizilla** [comment]
Need some help with a rollbar access token here
https://circleci.com/gh/ipfs-shipyard/peer-pad/301

@jimpick any ideas?

**Comment by jimpick** [comment]
> Need some help with a rollbar access token here
> https://circleci.com/gh/ipfs-shipyard/peer-pad/301
> 
> @jimpick any ideas?

I think @victorb has access to the token.

Thanks for doing this! I wasn't sure where to start.

**Comment by parkan** [comment]
@olizilla let me know if you need other tokens here -- I had assembled a partial set (no rollbar, though)

it might be useful to make this a passing failure, too

**Comment by olizilla** [comment]
@scout this config for the dev.peerpad.net didn't work

https://github.com/ipfs-shipyard/peer-pad/pull/294/files#diff-1d37e48f9ceff6d8030570cd36286a61R40

Do i need to adjust things so that it passes `peerpad.net` as the domain and `_dnslink.dev` as the record?

**Comment by parkan** [comment]
@olizilla dnsink-dnsimple operates at the zone level, so

> `peerpad.net` as the domain and `_dnslink.dev` as the record

should work

**Comment by jimpick** [comment]
Continuing the discussion over at #295

**Pull request merged**
