### PR TITLE
Tc/mobile nav

### PR DESCRIPTION
**Pull request by designsaves**

### CODE REVIEW

**Comment by olizilla** [comment]
@designsaves hi 👋, this PR isn't failing CI because of anything you did, it's just that CI using the old version of enzyme-to-json. If you want to fix this PR today then you'll need to manually add the missing line to the snapshot shown here: https://travis-ci.org/ipfs-shipyard/peer-pad/builds/376539290#L5081

It might be easier to wait for #164 to be merged and then update your PR from master.

**Comment by designsaves** [comment]
Thanks @olizilla I'll wait for #164 to be merged. Oh and hi! 👋

**Comment by one000mph** [comment]
@olizilla can this be merged now?

**Comment by jacobheun** [comment]
@designsaves #164 has been merged, you should be able to rebase from master and push now. The conflicts will need to get resolved, but that should fix the build failure.

**Comment by jacobheun** [comment]
@designsaves this looks good, but it looks like there is an issue with style changes in the internal mobile nav once you hit "start" and get into the application.

image

**Pull request merged**
