### PR TITLE
chore: anonomize rollbar data

### PR DESCRIPTION
**Pull request by victorb**
- Moved rollbar initialization to it's own file
- Real change is really the addition of `captureIp: false` and the
transformer that strips away the encryption key from request.url when
sent to rollbar

License: MIT
Signed-off-by: Victor Bjelkholm <git@victor.earth>

### CODE REVIEW

**Comment by victorb** [comment]
Realized that this is currently missing a check to make sure we're actually in a pad before trying to strip the last part of the URL. So don't merge this yet.

**Comment by victorb** [comment]
> Realized that this is currently missing a check to make sure we're actually in a pad before trying to strip the last part of the URL. So don't merge this yet.

Will not be a problem if we execute on https://github.com/ipfs-shipyard/pm-peer-pad/issues/35 as the only page that will exist, will be the page of a pad. So moving forward on that issue to unblock this PR.

**Comment by parkan** [comment]
let's merge this!

**Comment by victorb** [comment]
Fixed the merge conflict here and the cleanup of the frontend was merged, so this is good to go @pgte

**Comment by pgte** [comment]
@jimpick could you please review and merge this one?

**Comment by jimpick** [comment]
I'll merge it ... but I'm not a big fan of having deployment-specific stanzas with api keys, etc. in a codebase that also serves as an example app. I wonder if there's another pattern we can use?

**Pull request merged**
