### PR TITLE
feat: load testing

### PR DESCRIPTION
**Pull request by mkg20001**
This pr adds several load testing tests.

Would need some feedback on which kinds of load tests are needed.

### CODE REVIEW

**Comment by pgte** [comment]
@mkg20001 this is a great start, thank you!
Regarding #184, did you reach any conclusion as to the goal (150 concurrent users accessing the same pad, making a change every 0.5 seconds)?

**Comment by mkg20001** [comment]
@pgte No as I don't really have any statistics about the current loads of peer-pad. I think ~20 users making changes every ~1second should be a good baseline goal, but I don't know if peer-pad might already be used this heavily.

Additionally right now one of the load tests seems to fail, [this one](https://github.com/ipfs-shipyard/peer-pad/blob/bc008ec26f1f439a31ab711d22952da90c2b145e/test/e2e/load.test.js#L54-L79), although I'm unsure if this is a false positive because I'm using a hack to access the contents of the codemirror editor, something with timeouts, or if it really fails.

**Comment by pgte** [comment]
Then I suggest testing that using a local server and trying to push to see where we reach the limits.
(If you’re looking for a local server setup using aegir, I suggest you take a look at the current peer-star-app aegir setup.)

**Comment by pgte** [comment]
@mkg20001 did you get my previous comment?

**Comment by mkg20001** [comment]
> did you get my previous comment?

Not quite. I already have a local react dev server running, if that's what you mean. Also what I'm mainly missing is what else I could test the limits of. Right now just typing is tested.

**Comment by pgte** [comment]
I suggest the following:

* Have many peers (configurable) doing concurrent edits.
* Test how long it takes (on each peer) to reach convergence
* Output an average, standard deviation and 99 percentile for that measured convergence time.
* Allow establishing a baseline value for those measures (for instance, allow to define an absolute maximum for the 99th percentile of the convergence time)
* Discover the maximum number of peers after which the defined baseline is not respected (for instance, where P99 of the convergence time is bigger than the baseline)
* Publish those results.

Is this clear? Ping me if you have questions.

**Comment by mkg20001** [comment]
> standard deviation and 99 percentile

That is a bit unclear. This means getting rid of statistical flukes or basically values that diverge too far from the average, right?

> convergence time

Basically sync time?

> Publish those results.

Would publishing the code along with the result be good?

> Discover the maximum number of peers after which the defined baseline is not respected (for instance, where P99 of the convergence time is bigger than the baseline)

Unsure what is meant by "baseline". A maximum amount of time the process is allowed to take?

**Comment by pgte** [comment]
>> standard deviation and 99 percentile

> That is a bit unclear. This means getting rid of statistical flukes or basically values that diverge too far from the average, right?
It's being able to say 99 percent of cases sync in less than Y seconds.

>> convergence time

> Basically sync time?

Yes, of all the changes in all peers.

>> Publish those results.

> Would publishing the code along with the result be good?

You can publish the results in an issue or this PR.

>> Discover the maximum number of peers after which the defined baseline is not respected (for instance, where P99 of the convergence time is bigger than the baseline)

> Unsure what is meant by "baseline". A maximum amount of time the process is allowed to take?

Yes.

**Comment by olizilla** [comment]
This is rad, and a good generalisation of the smoke test to be more useful. 

I suggest not injecting jquery into the page during tests as it means the testing environment diverges from the production environment, which should be avoided. More significantly there are multiple  apis using `$` in the mix already, so it will be confusing for new developers. `document.querySelector` is much more verbose (_sigh_) but it is very clear which api and runtime is being targeted.

- puppeteer - https://github.com/GoogleChrome/puppeteer/blob/v1.6.0/docs/api.md#pageselector
- chrome dev tools - https://developers.google.com/web/tools/chrome-devtools/console/command-line-reference#queryselector)

**Comment by mkg20001** [comment]
After rebasing puppeteer stopped working, have no clue what's wrong. Still trying to figure that out...

**Comment by jacobheun** [comment]
@mkg20001 it looks like when travis got disabled the most recent update to the package-lock caused an issue with the test suite. Not sure if this is related to what you're hitting, but I am working on a fix for the test runner for Jenkins (https://github.com/ipfs-shipyard/peer-pad/issues/207)

**Comment by parkan** [comment]
is this superseded @pgte ?

**Comment by pgte** [comment]
@parkan yes it is.

**Comment by mkg20001** [comment]
Some of the improvements in making testing easier could also be gained by following the suggestion from #261

**Pull request closed without merging**
