### PR TITLE
chore: enable uglify compression

### PR DESCRIPTION
**Pull request by olizilla**
- Upgrade the uglifyjs-webpack-plugin to the latest.
- Update prod webpack conf with uglify settings to preserve names.

There is a weird issue that means the running the same
minification steps via a yarn installed dep tree vs an npm one
gives different results. This PR adds ensures that we get some
useful compression on our bundles but ensure that we dont break
IPFS while doing so.

The build now works on npm and yarn, which is nice, and local
testing suggest the IPFS boot time is much faster, which is ✨

License: MIT
Signed-off-by: Oli Evans <oli@tableflip.io>

### CODE REVIEW

**Comment by olizilla** [comment]
@fsdiogo could you give this a review pls? I'd love to get it merged. I know you've not worked on peer-pad, but your knowledge of react and create-react-app and the ipfs mangling issue more than qualify you!

**Comment by fsdiogo** [comment]
I had to pass another option to compress [here](https://github.com/ipfs/aegir/pull/214/files#diff-57a68f2746c4c8e4c9b2ef8fd17de515R43) to make `js-ipfs` work, so I'm not quite sure how you managed to bypass that 🤔

**Comment by olizilla** [comment]
@fsdiogo that's interesting... do you remember what failed if `compress: { unused: false }` was omitted? 

Possibly I'm seeing significant differences in the output bundles if the build is done with yarn or npm. With the previous, minimal uglify config that this PR changes, npm builds were functional, but yarn ones were unusable. Is aegir using yarn or npm under the hood?

**Comment by fsdiogo** [comment]
Yeah, it gave the following error when running `js-ipfs`:

```js
Uncaught (in promise) Error: Callback was already called
```

No idea why, I just thought that it could be solved by passing some options and `unused` did it.

>  Is aegir using yarn or npm under the hood?

I haven't poked around with aegir that much, don't know the answer to that straight away. But I can take a look if you need help.

**Comment by olizilla** [comment]
Ah, right, so I saw that error if I omitted `keep_fnames: true,` from mangle and compress options. I'll try replacing that with just `unused: true` and see what difference it makes.

**Comment by fsdiogo** [comment]
Cool! Although you'll have to `keep_fnames: true` until 0.29.0 lands, or else `js-ipfs` will break.

**Comment by olizilla** [comment]
@fsdiogo `keep_classnames: true` and `unused: true` works. `keep_fnames` doesn't seem to be needed.

**Comment by fsdiogo** [comment]
@olizilla oops sorry, I wrote `keep_fnames` but I was thinking of `keep_classnames` 😛

Yeah, I don't think we type check using function names so that shouldn't be a problem 👍

**Pull request merged**
