### PR TITLE
WIP: Chore/upgrade deps

### PR DESCRIPTION
**Pull request by pgte**

### CODE REVIEW

**Comment by pgte** [comment]
Currently failing with:

```
this.htmlWebpackPlugin.getHooks is not a function
```

**Comment by pgte** [comment]
@satazor do you think you can help with your webpack chops here? :)

**Comment by satazor** [comment]
It seems that the build script needs to be updated, because this seems like an ejected CRA correct?

**Comment by satazor** [comment]
Moreover, there's stuff that should be copied as well, such `jest` config: https://github.com/ipfs-shipyard/peer-pad/blob/4ba773f65c43de46989fb99fee5bde3bed53fd92/package.json#L105

@pgte want to me take a stab on this or my suggestions are sufficient?

**Comment by pgte** [comment]
@satazor could you please lend a hand here?

**Comment by satazor** [comment]
Will do.

**Comment by satazor** [comment]
@pgte Here it is: https://github.com/ipfs-shipyard/peer-pad/pull/239

Please read the PR description as it contains valuable info.

**Comment by jimpick** [comment]
I'm going to try to freshen this up and get the deps upgraded...

**Comment by jimpick** [comment]
I'm going to merge these ... there's a few more to upgrade - I'll do those in a separate PR.

**Pull request merged**
