### PR TITLE
Add mockup styling to Features section

### PR DESCRIPTION
**Pull request by lynnandtonic**
This pull request adds the globe illustration and dotted lines to the "Features" section per the mockup @akrych provided.

Largest screen size has them in the four quadrants. Smaller screens break it down to two columns and then single column for smallest screen size. 

I didn't add animation just yet, which I think will take a bit more effort and this is an improvement we can make right away.

image

image

image

### CODE REVIEW

**Comment by lynnandtonic** [comment]
cc @diasdavid

**Comment by akrych** [comment]
I can't review the code (I'm only graphic designer;) so @pgte ?

**Comment by lynnandtonic** [comment]
Thanks! @pgte Are those failing tests an issue?

**Comment by lynnandtonic** [comment]
@pgte I'm a bit stuck on the CI issue. I'm guessing it's the image paths I declared, but I'm not sure what I've gotten wrong. Any ideas?

**Comment by lynnandtonic** [comment]
I also adjusted the copy styling for the "What you can do with Peer Pad" section to better match the "Features" section for consistency.

image

**Comment by pgte** [comment]
@lynnandtonic looks like your CI issues are solved (except for circle CI, which I wouldn't care about).

**Comment by lynnandtonic** [comment]
@pgte Ah ok, good to know. Thanks! Going to merge. ✨

**Pull request merged**
